title: Introduction to Data Science I & II
author: the University of Chicago
copyright: "2022"
logo: "images/logo/uchicago_python_nobackground.png"  # path to a logo file

sphinx:
  config:
    execution_show_tb: true
    html_favicon: favicon.ico
  extra_extensions:
    - sphinx_proof

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_image
